//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int PictureId { get; set; }
        public string PictureLocation { get; set; }
        public int BasketId { get; set; }
        public byte[] BidTime { get; set; }
    
        public virtual Basket Basket { get; set; }
    }
}
